Tasks ended
Angstreminus/hw2 pull request #1
Opened 2023-10-28 14:51 UTC by Angstreminus

Задачи закрыты(вроде). Надеюсь понравится и ничего не упустил)
TODO:
Makefile

2023-11-01 19:02 UTC, Yu-Leo requested changes
1. Респект за тесты! 🔥🔥🔥
2. Решение крутое. Замечания по большей части небольшие. Как поправишь, напиши, пожалуйста, в комментариях к PR слово "ИСПРАВЛЕНО", чтобы я видел, что всё готово и можно ещё раз глянуть.

2023-11-01 20:47 UTC, Angstreminus commented on task-1/task1.go
> +	a_t, b_t := float64(a), float64(b)
Согласен, недоглядел.

2023-11-01 20:49 UTC, Angstreminus commented on task-1/task1_test.go
> +func Test_validateInput(t *testing.T) {
Читал, что тесты в целом принято обозначать чтобы гошка понимала что это тесты Test_<Name>, потестил Test<Name> и в целом принял, спасибо поправлю.

2023-11-01 20:51 UTC, Angstreminus commented on task-3/task3_test.go
> +			assert.Equal(t, res, test.want)
Спасибо, учту)

2023-11-06 18:13 UTC, Angstreminus commented
Fixed.
Makefile поленился писать, но написал скрипт запуска тестов)
Надеюсь ничего не упустил, сделал задчку 5 ручками.

2023-11-06 18:23 UTC, Angstreminus commented
Fixed

2023-11-06 18:38 UTC, Angstreminus reviewed
Fixed

2023-11-09 13:32 UTC, Yu-Leo approved these changes
**Аппрув!** 🎆 

ДЗ принято.

Замечание маленькое, поправь и можешь смерджить ветки.

Ещё раз респект за тесты и за скрипт для тестирования 🔥

Для будущих домашек: не нужно повторно кидать ссылку на PR через форму. Просто напиши слово "ИСПРАВЛЕНО" прям тут, в обсуждении PR

2023-11-09 13:32 UTC, Yu-Leo commented on task-6/task6.go
> +	return cnt
При первом ревью проглядел, на самом деле можно ведь ещё сильнее упроситить. Счетчик не нужен, можно просто выводить длинну мапки

```go
dict := make(map[int]struct{})
for _, elem := range arr {
	if _, ok := dict[elem]; !ok {
		dict[elem] = struct{}{}
	}
}	
return len(dict)
```

2024-03-22 21:16 UTC, merged